/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package First_Java_Gradle_Project;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
